server:
  port: 80 # 网关一般是80
spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      enabled: true # =只要加了依赖 默认开启
      discovery:
        locator:
          enabled: true # 开启动态路由
          lower-case-service-id: true # 开启服务名称小写
      routes: # 如果一个服务里面有100个路径  如果我想做负载均衡 ??   动态路由
        -   id: login-service-route  # 这个是路由的id 保持唯一即可
          #                    uri: http://localhost:8080   # uri统一资源定位符   url 统一资源标识符
#            uri: http://localhost:8585   # uri统一资源定位符   url 统一资源标识符
            uri: lb://login-service
            predicates: # 断言是给某一个路由来设定的一种匹配规则 默认不能作用在动态路由上
              - Path=/doLogin  # 匹配规则  只要你Path匹配上了/doLogin 就往 uri 转发 并且将路
#              - Query=name,/^[0-9]{3}/  # 查询必须带参数,Query后面的是参数名称name,name后的是正则表达式
#              - After=2024-03-22T08:42:59.521+08:00[Asia/Shanghai]  # 时间要在这之后
#              - Method=GET,POST # 只允许Get和Post请求
eureka:
  client:
    service-url:
      defaultZone: http://peer1:8761/eureka
    #   是否往eureka里面注册
    register-with-eureka: true
    #    是否去拉去服务列表
    fetch-registry: true
    #    每隔多少秒去拉取一次列表,为了防止脏读,时间越短,脏读越小,但资源消耗越多
    registry-fetch-interval-seconds: 3
  instance:
    hostname: localhost
    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10