# 集群配置
server:
  port: 8763
spring:
  application:
    name: eureka-server
eureka:
  client:
    # 不写,默认往8761里面注册
    service-url:
      defaultZone: http://peer1:8761/eureka,http://peer2:8762/eureka
  instance:
    #    主机名称 : 应用名称 : 端口号
    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port}
    #    主机名称 或者服务的ip
    hostname: peer3
    # 以ip的形式显示具体的服务信息
    prefer-ip-address: true
    # 服务实例的续约的时间间隔
    lease-renewal-interval-in-seconds: 5