#单机配置
server:
  port: 8761
spring:
  application:
    name: eureka-server
eureka:
  server:
# 服务端间隔多少毫秒做定期删除的操作,删除那些与服务端断开联系的客户端
    eviction-interval-timer-in-ms: 10000
# 约百分比 超过85%的应用没有和你续约 那么eureka会保护服务 不会剔除任何一个
    renewal-percent-threshold: 0.85
  instance:
#    主机名称 : 应用名称 : 端口号
    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port}
#    主机名称 或者服务的ip
    hostname: peer
    # 以ip的形式显示具体的服务信息
    prefer-ip-address: true
    # 服务实例的续约的时间间隔
    lease-renewal-interval-in-seconds: 5


# 集群配置
#server:
#  port: 8761
#spring:
#  application:
#    name: eureka-server
#eureka:
#  client:
## 不写,默认往8761里面注册
#    service-url:
#      defaultZone: http://peer2:8762/eureka,http://peer3:8763/eureka
#  instance:
##    主机名称 : 应用名称 : 端口号
#    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port}
##    主机名称 或者服务的ip
#    hostname: peer1
#    # 以ip的形式显示具体的服务信息
#    prefer-ip-address: true
#    # 服务实例的续约的时间间隔
#    lease-renewal-interval-in-seconds: 5

# 集群终极方案配置
#server:
#  port: 8761
#spring:
#  application:
#    name: eureka-server
#eureka:
#  client:
## 不写,默认往8761里面注册
#    service-url:
#      defaultZone: http://peer1:8761/eureka,http://peer2:8762/eureka,http://peer3:8763/eureka
#  instance:
##    主机名称 : 应用名称 : 端口号
#    instance-id: ${spring.application.name}:${server.port}
##    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port}
##    主机名称 或者服务的ip
##    hostname: peer1
#    # 以ip的形式显示具体的服务信息
#    prefer-ip-address: true
#    # 服务实例的续约的时间间隔
#    lease-renewal-interval-in-seconds: 5